config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/home/prices', to: 'home#prices'
  post '/home/prices', to: 'home#prices'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    require 'net/http'
    require 'json'
    # Get price data
    @price_url = 'https://min-api.cryptocompare.com/data/pricemultifull?fsyms=BTC,ETH,BNB,USDT,ADA,DOGE,XRP,DOT,USDC,UNI&tsyms=USD'
    @price_uri = URI(@price_url)
    @price_response = Net::HTTP.get(@price_uri)
    @prices = JSON.parse(@price_response)

    # Get news data

    @url = 'https://min-api.cryptocompare.com/data/v2/news/?lang=EN'
    @uri = URI(@url)
    @response = Net::HTTP.get(@uri)
    @news = JSON.parse(@response)
  end

  def prices
    require 'net/http'
    require 'json'
    @symbol = params[:sym]
    if @symbol.present?
      @symbol = @symbol.upcase

      # Get price data
      @quote_url = 'https://min-api.cryptocompare.com/data/pricemultifull?fsyms=' + @symbol + '&tsyms=USD'
      @quote_uri = URI(@quote_url)
      @quote_response = Net::HTTP.get(@quote_uri)
      @quote = JSON.parse(@quote_response)
    end

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to "Crypto News Network", root_path, class:'navbar-brand mx-4'  %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Get Prices", home_prices_path, class:'nav-link'  %>
        </li>
      </ul>
        <%= form_tag('/home/prices', method: 'get') do %>
          <%= text_field_tag 'sym', nil, placeholder: 'Enter Crypto Symbol' %>
          <%= submit_tag("Submit") %>
        <% end %>
    </div>
  </div>
</nav>

app/views/home/index.html.erb
<!-- coins table -->
<table class="table table-striped table-bordered table-hover border-dark">
  <thead class="thead-dark">
    <tr>
      <th scope="col">No.</th>
      <th scope="col">Name</th>
      <th scope="col">Price</th>
      <th scope="col">24hr High</th>
      <th scope="col">24hr Low</th>
      <th scope="col">Market Cap</th>
    </tr>
  </thead>
  <% i = 1 %>
  <% base = "https://cryptoicon-api.vercel.app/api/icon/" %>
  <tbody>
    <% @prices["DISPLAY"].each do |k, y| %>
    <% coin_img = base+k.downcase %>
    <tr>
      <td><%= i %></td>
      <td><img src="<%= coin_img %>" alt="<% k %>" width="30" height="30" class="me-3"><%= k %></td>
      <td><%= y["USD"]["PRICE"] %></td>
      <td><%= y["USD"]["HIGHDAY"] %></td>
      <td><%= y["USD"]["LOWDAY"] %></td>
      <td><%= y["USD"]["MKTCAP"] %></td>
    </tr>
    <% i += 1 %>
  <% end %>
  </tbody>
</table>
<br/><hr/><br/>

<!-- news cards here -->
<div class="container">
  <div class="row">
    <% @news["Data"].each do |n|  %>
        <div class="col-sm">
          <div class="card" style="width: 18rem;">
            <img src="<%= n["imageurl"]  %>" class="card-img-top" alt="<%= n["source"] %>">
            <div class="card-body">
              <h5 class="card-title"><%= n["body"] %></h5>
              <p class="card-text"><%= n["body"] %></p>
              <a href="<%= n["url"] %>" class="btn btn-secondary">Read more... </a>
            </div>
          </div>
        </div>
        <br/>
    <% end %>
  </div>
</div>

app/views/home/prices.html.erb
<br>
<% if @symbol %>
  <% @quote["DISPLAY"].each do |k, y| %>
    <div class="card-header w-50">
      <div class="card-body">
        <h5 class="card-title"><%= k %></h5>
          Price: <%= y["USD"]["PRICE"] %></br>
          24Hr High: <%= y["USD"]["HIGHDAY"] %></br>
          24Hr Low: <%= y["USD"]["LOWDAY"] %></br>
          Market Cap: <%= y["USD"]["MKTCAP"] %></br>
      </div>
    </div>
  <% end %>
  <% else %>
    <%# <form> %>
    <h5>Please enter a symbol</h5>
    <%= form_tag('/home/prices', method: 'get') do %>
      <%= text_field_tag 'sym', nil, placeholder: 'Enter a crypto symbol' %>
      <%= submit_tag("Submit") %>
    <% end %>
 <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Crypto News Network</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'home/navbar' %>
    <br/>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>